
pipeline {
    agent any
    stages {
        stage ('git push'){
            steps {
                git branch: 'master', url: 'https://github.com/gabriel-saraiva-garcia/Alpine-Flask-App.git'
            }   
        }

        stage ('build') {
            steps {
                sh 'docker build -t flask .'
            }
        }
    }
}
